#ifndef DEVICE_DATA_H_
#define DEVICE_DATA_H_

#define OPENER_DEVICE_VENDOR_ID      1
#define OPENER_DEVICE_TYPE           12
#define OPENER_DEVICE_PRODUCT_CODE   1
#define OPENER_DEVICE_MAJOR_REVISION 1
#define OPENER_DEVICE_MINOR_REVISION 0
#define OPENER_DEVICE_NAME           "VARD EtherNet/IP Device"

#endif

